name: build my app!

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v2

      - name: print CWD
        run: pwd

  